### ISSUE TITLE
Server side?

### ISSUE THREAD

**Issue by Jipok** [TheIncgi/AdvancedMacros-1.12.2#23]
I love lua for moding. And I really don't like languages like java.

Can your mod be used as a replacement for CraftTweaker(deleting/changing crafting recipes)? 
I would love to throw out Kiwi, InControl, CraftTweaker, SpawnInVillage, Neat, Areas, logprot, TelePass, etc. And rewrite them in lua. Most of these mods are very easy to implement and only require a couple of methods from the server.

If this mod is only for the client, is it difficult to rewrite to support simple server-side actions?

**Comment by big-lip-bob** [comment]
To me this sounds like a job for [Cuberite](https://cuberite.org/)

**Comment by Jipok** [comment]
> To me this sounds like a job for Cuberite

I know about this project. But this is only a server. And only for old versions of minecraft, and not full support.
I wanted the lua code in addition to the existing mods. For both the client and the server. Developing this theme, you can create powerful mods adding new content.

**Comment by big-lip-bob** [comment]
a Lua based modloader is possible but tha'd be quite tedious, and i doubt its within the scope of this mod too. altough we'd need to see what the dev thinks about it

**Comment by TheIncgi** [comment]
Late reply, but to answer, this mod is all client side.
Server sided features have been frequently requested but the mod was not designed with it in mind and would be a large task.

It hasn't been ruled out completely, but it's not likely in the near future.

**Comment by MajsterTynek** [comment]
https://www.wizards-of-lua.net/
https://github.com/wizards-of-lua/wizards-of-lua
the only disadvantage is that is only for 1.12
