### ISSUE TITLE
Cannot identify and proceed color code

### ISSUE THREAD

**Issue by FYWinds** [TheIncgi/AdvancedMacros-1.12.2#39]
Seems that all common str functions in lua are not using any unicode-aware algorithm, so there's no way to detect the color character `§` which is `\u00a7`. Is there any way to deal with the color code?

**Comment by FYWinds** [comment]
I found one inelegant way to detect it is to convert the entire string to bytes and parsing it by bytes.

**Comment by MajsterTynek** [comment]
could you show some code snippets where you think they are faulty?

**Comment by FYWinds** [comment]
```lua
entity1_name = "§c Hostile mob§6 [Lv.20]"
entity2_name = "§a Friendly mob§6 [Lv.20]"
```
I want to match the hostile one. The only discriminator is the color of the name.
I found this project is using luaj and the luaj project implements lua 5.2
As said by the lua-users.wiki that lua stores strings by bytes, so we can actually use the unicode extended characters.

> Lua's pattern matching facilities work byte by byte. In general, this will not work for Unicode pattern matching, although some things will work as you want.

So I tried and found that functions such as `string.find` `string.gmatch` `string.sub` ALL CANNOT process the color code `§` properly

```lua
pattern = "§c.*§6 %[Lv.*"
if string.find(entity1_name, pattern) ~= nil then
    log("match entity1")
end
if string.find(entity2_name, pattern) ~= nil then
    log("match entity2")
end
-- this will output match entity1, which means it works
-- but why?
```

I did some further searching and testing, and finally found that the `§` character written in a lua file is different the one I get from getEntity().name

```lua
entity_name = "§c T" -- It's a test so make it as short as possible
entity2_name = getEntityList()[1].name

-- This part convert the string to bytes array
tmp = {}
for c in entity_name:gmatch(".") do
    table.insert(tmp, c:byte())
end
tmp2 = {}
for c in entity2_name:gmatch(".") do
    table.insert(tmp2, c:byte())
end

log(tmp)
-- output: [230, 144, 130, 99, ...]
-- 99 -> c so the § character written in file is processed into the array [230, 144, 130, 99]
log(tmp2)
-- output: [194, 167, 99, ...]
-- so the § character got from AdvancedMacro's function is [194, 167]
```

So my fix to this is to actually write a comparison byte to byte.
```lua
if tmp[1] == 194 and tmp[2] == 167 and tmp[3] == 99 then -- This detects '§c'
    for num, x in pairs(tmp) do
        if x == 194 and tmp[num + 1] == 167 and tmp[num + 2] == 54 and tmp[num + 3] == 32 and tmp[num + 4] == 91 then -- This detects '§6 [L'
            return true
        end
    end
end
```

If my words confuse you please be sure to ask me what I mean because I am not a native English speaker.

**Comment by MajsterTynek** [comment]
That `"§c T"` should return `[194, 167, 99, 32, 84]`.
You may type `\xC2\xA7` for `§` character, which is `[194, 167]`.
Lua files are not Unicode aware, because they let strings to be anything including zeros.
You need to treat bytes as already encoded as `utf-8` sequence.
https://en.wikipedia.org/wiki/UTF-8#Encoding

Try running following example.
Issue might be a different file encoding than UTF-8,
or AdvancedMacros derieves from your locale.
```lua
local para1 = "§c T"
local para2 = "\xC2\xA7c T"
local isok = para1 == para2

if not isok then
    log{para1:byte(1,-1)}
    log{para2:byte(1,-1)}
end

isok = isok and "OK" or "NOK"
log("&3String compare: &b"..isok)
```
