### ISSUE TITLE
Fabric and newer minecraft versions

### ISSUE THREAD

**Issue by UltraBlackLinux** [TheIncgi/AdvancedMacros-1.12.2#44]
Hey there,
This mod was one of my favourites back when I used 1.12.2, but not only did I switched to fabric for it's launch speed and lower ram consumption, but I also switched to more recent minecraft versions and I've been missing this ever since.

Could you add a fabric port and also support the more recent versions?

Thanks!

**Comment by MajsterTynek** [comment]
There was an attempt in our community. It is mostly incomplete tho
https://github.com/Etheradon/AdvancedMacros/tree/1.19-dev

**Comment by UltraBlackLinux** [comment]
> There was an attempt in our community. It is mostly incomplete tho https://github.com/Etheradon/AdvancedMacros/tree/1.19-dev

Oh I didn't know that! I hope it'll work :)

**Comment by k4ey** [comment]
#45  adds this. Can close
